### ISSUE TITLE
Crosstab Function

### ISSUE THREAD

**Issue by nurahjaradat** [Rkabacoff/qacr#6]
We're still having some trouble getting our code to run, and need to revisit this. Specifically, we're having trouble with nonstandard evaluation and the base R table function.

**Comment by Rkabacoff** [comment]
Try this

crosstab <- function(data, rowvar, colvar,
                     type=c("freq", "rowpercent", "colpercent"),
                     total=TRUE, na.rm=FALSE,
                     digits=2){
  
  rowvar <- deparse(substitute(rowvar))
  colvar <- deparse(substitute(colvar))
  
  if (!is.factor(data[rowvar]))
    data[rowvar] <- as.factor(data[[rowvar]])
  if (!is.factor(data[colvar]))
    data[colvar] <- as.factor(data[[colvar]])
  
  t <- table(data[[rowvar]], data[[colvar]])

**Comment by Rkabacoff** [comment]
Hi Nurah,

I found the problems and I can suggest fixes. Can your team meet after class tomorrow?

All the best,

RobK
_______________________
Rob Kabacoff, Ph.D
Professor of the Practice
Quantitative Analysis Center
Wesleyan University
222 Church Street
Middletown, CT 06459
(860) 685-2759

**Comment by nurahjaradat** [comment]
We fixed the code for cross tab and also added the print.crosstab function.
